{% set name = "smartystreets_python_sdk" %}
{% set version = "4.14.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/smartystreets_python_sdk-{{ version }}.tar.gz
  sha256: 1c6765150dbe24e9c8e01a6a61eecdaaaafdc92e7f440af335720d3f7b30ebaa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5|>=2.7
  run:
    - python >=3.5|>=2.7
    - requests

test:
  imports:
    - smartystreets_python_sdk
    - smartystreets_python_sdk.international_street
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/smartystreets/smartystreets-python-sdk
  summary: An official library to help Python developers easily access the SmartyStreets APIs
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - melonhead901
