{% set name = "smartystreets_python_sdk" %}
{% set version = "4.13.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/smartystreets_python_sdk-{{ version }}.tar.gz
  sha256: 1d3cd5062662fe26f1bdfc3ed3e112d5d7abe76d6df5b452f7e00b84a4f19deb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5|>=2.7
  run:
    - python >=3.5|>=2.7
    - requests

test:
  imports:
    - smartystreets_python_sdk
    - smartystreets_python_sdk.international_street
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/smartystreets/smartystreets-python-sdk
  summary: An official library to help Python developers easily access the SmartyStreets APIs
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - melonhead901
