{% set name = "smartystreets_python_sdk" %}
{% set version = "4.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/smartystreets_python_sdk-{{ version }}.tar.gz
  sha256: 3dd626fca7ec1c76808977883cd0af3ea1730b7ade6211904ffcd19e3f049e43

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7.*|>=3.5.*
  run:
    - python >=2.7.*|>=3.5.*
    - requests

test:
  imports:
    - smartystreets_python_sdk
    - smartystreets_python_sdk.international_street
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/smartystreets/smartystreets-python-sdk
  summary: An official library to help Python developers easily access the SmartyStreets APIs
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - melonhead901
