{% set name = "smartystreets_python_sdk" %}
{% set version = "4.16.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/smartystreets_python_sdk-{{ version }}.tar.gz
  sha256: cb80c4fffccb578f49d3d384fd364d8b551fa10a70a174ed3d0a8b51c63e4ae1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5|>=2.7
  run:
    - python >=3.5|>=2.7
    - requests

test:
  imports:
    - smartystreets_python_sdk
    - smartystreets_python_sdk.international_street
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/smartystreets/smartystreets-python-sdk
  summary: An official library to help Python developers easily access the SmartyStreets APIs
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - melonhead901
